void initVisuals();
void updateVisuals();
void playPatternAlarmAttractorPattern();
void loopAlarmAttractor();
void waitForKnockVisuals();
void knockPattern();
void playPattern(int ptrnIndex, long duration = 500);
void playRangePattern(int offset, int num);
void highlightSection(int section);
void playPatternTryDoorKnob();
void playPatternDoorKnobHeld();
void playPatternTorchAttractor();
void playPatternTorchDetected();
void playPatternKeyAttractor();
void playPatternFinale_1();
void playPatternFinale_2();
void playPatternFinale_3();
void playPatternFinale_4();
void playPatternFinale_5();
void playPatternFinale_6();
void playPatternFinale_7();

